# Spiegazione: array, liste...

In [1]:
# librerie:
import sys
sys.path.insert(0, 'C:\Users\Camilla Bianca\Documents\GGPL\lar-cc\larlib')
from larlib import *

Evaluating fenvs.py..
...fenvs.py imported in 0.00742255078434 seconds


In [2]:
AA(SUM)([[1,2,3],[4,5,6]])

[6, 15]

In [3]:
# La funzione SUM viene applicata a tutti gli elementi della sequenza: somma il primo array al secondo.

In [4]:
mat = [[1,2,3],[4,5,6]]

In [5]:
[sum(v) for v in mat]

[6, 15]

In [6]:
# Abbiamo assegnato una funzione ad una variabile, ma il risultato è quello!

In [7]:
DISTL([2,[1,2,3]])

[[2, 1], [2, 2], [2, 3]]

In [8]:
# Distribuisce l'elemento di sinistra sugli elementi della lista di destra: la semantica è proprio
# ([elemento, [lista]])

In [9]:
DISTR([[1,2,3,4],9])

[[1, 9], [2, 9], [3, 9], [4, 9]]

In [10]:
# Fa la stessa cosa di DISTL, ma sulla destra!

# TRANS prende una lista di liste e scambia le righe con le colonne:

In [11]:
TRANS([[1,2,3],[10,20,30],[100,200,300]])

[[1, 10, 100], [2, 20, 200], [3, 30, 300]]

In [12]:
a = [[1,2,3],[10,20,30],[100,200,300]]

In [13]:
np.array(a)

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [14]:
np.transpose(np.array(a))

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300]])

In [15]:
(np.transpose(np.array(a))).tolist()

[[1, 10, 100], [2, 20, 200], [3, 30, 300]]

In [16]:
# Abbiamo fatto la stessa cosa, ma con numpy!
# Con tolist() l'abbiamo fatta ridiventare una lista!

In [17]:
PROD([3,4])

12

In [18]:
PROD([[1,2,3],[4,5,6]])

32.0

In [19]:
SUM([3,4])

7

In [20]:
# Prodotto di uno scalare per un vettore:
SCALARVECTPROD([3,[1,2,3]])

[3, 6, 9]

In [21]:
# In numpy:
3*np.array([1,2,3])

array([3, 6, 9])

In [22]:
# Il prodotto tra due array è più espressivo se scritto in questo modo:
INNERPROD([[1,2,3],[10,20,30]])

140

In [23]:
# Norma di un vettore: Radice quadrata della somma dei componenti
a = [1,2,3]

In [24]:
VECTNORM(a)

3.7416574954986572

In [25]:
# Somma di matrici:
A = [[1,2,3],[4,5,6],[7,8,9]]
B = [[10,20,30],[40,50,60],[70,80,90]]

In [26]:
# Transponiamo:
TRANS([A,B])

[[[1, 2, 3], [10, 20, 30]],
 [[4, 5, 6], [40, 50, 60]],
 [[7, 8, 9], [70, 80, 90]]]

In [27]:
(AA(TRANS)(TRANS([A,B])))

[[[1, 10], [2, 20], [3, 30]],
 [[4, 40], [5, 50], [6, 60]],
 [[7, 70], [8, 80], [9, 90]]]

In [28]:
## AA fa penetrare entro un livello di parentesi
# AA(AA()) fa penetrare entro due livelli di parentesi
AA(AA(SUM))(AA(TRANS)(TRANS([A,B])))

[[11, 22, 33], [44, 55, 66], [77, 88, 99]]

In [29]:
# Prodotto matriciale: di solito si usa il triplo ciclo! Qui invece si usano le formule matematiche:
def MATPROD(args):
    A,B=args
    return AA(AA(INNERPROD))(AA(DISTL)(DISTR([A,TRANS(B)])))
#prendo le righe del primo argomento, le colonne del secondo, le accoppio e faccio sopra i prodotti scalari!!

In [30]:
MATPROD([A,A])

[[30, 36, 42], [66, 81, 96], [102, 126, 150]]

In [31]:
# in più passi, con A e B:
[A,TRANS(B)]

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 40, 70], [20, 50, 80], [30, 60, 90]]]

In [33]:
DISTR([A,TRANS(B)])

[[[1, 2, 3], [[10, 40, 70], [20, 50, 80], [30, 60, 90]]],
 [[4, 5, 6], [[10, 40, 70], [20, 50, 80], [30, 60, 90]]],
 [[7, 8, 9], [[10, 40, 70], [20, 50, 80], [30, 60, 90]]]]

In [34]:
AA(DISTL)(DISTR([A,TRANS(B)]))

[[[[1, 2, 3], [10, 40, 70]],
  [[1, 2, 3], [20, 50, 80]],
  [[1, 2, 3], [30, 60, 90]]],
 [[[4, 5, 6], [10, 40, 70]],
  [[4, 5, 6], [20, 50, 80]],
  [[4, 5, 6], [30, 60, 90]]],
 [[[7, 8, 9], [10, 40, 70]],
  [[7, 8, 9], [20, 50, 80]],
  [[7, 8, 9], [30, 60, 90]]]]

In [35]:
AA(AA(INNERPROD))(AA(DISTL)(DISTR([A,TRANS(B)])))

[[300, 360, 420], [660, 810, 960], [1020, 1260, 1500]]

In [36]:
# Per applicare ciò, numero rghe della prima = numero colonne della seconda!
array(A)*array(B)

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [37]:
N(3) (0)

[0, 0, 0]

In [38]:
 N(3) ([0,1])

[[0, 1], [0, 1], [0, 1]]

In [39]:
# NN si applica alle liste: restituisce liste concatenate
NN(3)([0,1])

[0, 1, 0, 1, 0, 1]

In [40]:
AR([[0,0,0],1])

[0, 0, 0, 1]

In [41]:
AL([1,[0,0,0]])

[1, 0, 0, 0]

In [42]:
# Il prodotto vettore restituisce un vettore ed è definito solo in R^3!
# def VECTPROD ...

In [43]:
from random import random

In [44]:
def randomPoints(m,sx=1,sy=1): #sx = coefficiente di scala, per spostare i punti nell'intervallo che voglio
    def point():
        return [random()*sx,random()*sy]
    return [point() for k in range(m)]

In [45]:
verts = randomPoints(200,2*PI,2) #l'ascissa (x) varia tra 0 e 2PI, mentre l'ordinata (y) varia tra 0 e 2!

In [46]:
obj = MKPOL([verts,AA(LIST)(range(200)), None]) #AA(LIST) fa diventare tutti i vertici una lista!

In [47]:
help(random)

Help on built-in function random:

random(...)
    random() -> x in the interval [0, 1).



In [48]:
VIEW(obj)

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000E71A4E0> >

In [49]:
# Prendo un punto e trasformo le sue coordinate da cartesiane a polari:
def x(p):
    u,v = p
    return v*COS(u)

In [50]:
def y(p):
    u,v=p
    return v*SIN(u)

In [51]:
obj = MAP([x,y])(obj)

In [52]:
VIEW(obj)

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x000000000E71AF30> >

In [53]:
# MAP prende una lista di funzioni coordinate ed un dominio, ed applica a tutti i vertici di quel
# dominio le funzioni che trova nella lista

In [54]:
#################################################
########### MODELLAZIONE DI SOLIDI: #############
#################################################
#SCHEMA DI RAPPRESENTAZIONE: Una funzione F che va da uno spazio di modelli matematici (M) ad uno spazio di
# rappresentazioni simboliche di quest'ultime (R).
# Di solito non si riesce a rappresentare tutti i modelli in un solo schema: esiste infatti un Dominio dello schema.
# M potrebbe essere il disegno di un poligono sul piano; R potrebbe essere una lista concatenata che contiene
# i vertici del poligono!